### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by DanielGenser** [WickyNilliams/headroom.js#138]
I'm having trouble getting this work on my test page.

I call headroom.js then initialize it using vanilla JS: 

```javascript
    <script type="text/javascript">
      var myElement = document.querySelector(".navbar");
      var headroom  = new Headroom(myElement);

      headroom.init();
    </script>
```

This is the CSS I'm using to style things:

```css
.navbar	{
	position: fixed;
	height: 80px;
	bottom: 0;
	left: 0;
	width: 100%;
}
.headroom {
    transition: transform 200ms linear;
}
.headroom--pinned {
    transform: translateY(-100%); 
}
.headroom--unpinned {
   transform: translateY(0%);	
}
```
However, I get the following console error each time: 

Uncaught TypeError: 
Cannot read property 'classList' of null headroom.js:139 
Headroom.init headroom.js:139 
(anonymous function)(index):40 

The weird thing is that .navbar definitely exists in the HTML. I've tried other elements, too, same problem. What really obvious thing am I failing to see?
