### ISSUE TITLE
Provide some CSS defaults

### ISSUE THREAD

**Issue by pensierinmusica** [WickyNilliams/headroom.js#155]
Hi,

This is library is a great work, thanks for publishing it! It would be even more awesome if it provided some default CSS that can be imported into the HTML file to get a few basic behaviors.

For example today I lost almost two hours digging into the [playroom]( http://wicky.nillia.ms/headroom.js/playroom/) to find out that `animation-fill-mode: both;` is an essential property when using the "slide" animation (which is not documented anywhere).

Any possibility to implement some default styles?

Thanks! Cheers

**Comment by WickyNilliams** [comment]
I've been meaning to clean up the CSS in the playroom. Currently it uses keyframe animations for slide, which is far too complex. The documentation covers some basic CSS to get you going. Effectively, something like this:

```css
/**
 * Note: I have omitted any vendor-prefixes for clarity.
 * Adding them is left as an exercise for the reader.
 */
.headroom {
    transition: transform 200ms linear;
}
.headroom--pinned {
    transform: translateY(0%);
}
.headroom--unpinned {
    transform: translateY(-100%);
}
```
