### ISSUE TITLE
Incompatible with Angular Material

### ISSUE THREAD

**Issue by norkunas** [WickyNilliams/headroom.js#164]
Angular material uses ```offset``` attribute for flex layout, so when passing the ```offset``` for headroom material also applies it's css.

**Comment by Stamy** [comment]
It's working fine for my for angular material. Don't forget to set z-index for headroom, because angular material uses it, so it might be working but you can't see.

**Comment by norkunas** [comment]
@Stamy how can they work together if they use the same attribute for different purposes?

**Comment by Stamy** [comment]
It works fine for the md-toolbar. Here is my css, the only thing I had to do is to wrap the toolbar with `<div style="height: 64"></div>`  not to loose the height in the template when md-toolbar becomes flexible.

```css
.headroom {
    transition: transform 200ms linear;
}

.headroom--not-top {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 99999;
}

.headroom--pinned {
    transform: translateY(0%);
}

.headroom--unpinned {
    transform: translateY(-100%);
}

```
