### ISSUE TITLE
Headroom directive don't works with Ionic Framework

### ISSUE THREAD

**Issue by EricDosReis** [WickyNilliams/headroom.js#175]
Hi! Thanks for build this resource!

Eeeh, I tried implement headroom angular directive with Ionic Framework, but don't worked.

See my code:

```html
<ion-header-bar class="bar-custom" align-title="left"
	headroom>
	<h1 class="title">{{ viewTitle }}</h1>

	<div class="buttons">
		<button class="button button-clear button-icon icon ion-android-search"
			ng-click="showFilterBar()">
		</button>
	</div>
</ion-header-bar>
```

```css
.headroom { transition: transform 200ms linear }

.headroom--pinned { transform: translateX(0%) }

.headroom--unpinned { transform: translateX(-50%) }
```

Can you help me?
