### ISSUE TITLE
Option to add classes to body instead of header element?

### ISSUE THREAD

**Issue by jpt** [WickyNilliams/headroom.js#231]
Forgive me if this is documented elsewhere, but is it possible to have Headroom apply classes to the body rather than the header element? The use case I'm thinking of is a nav bar that is relatively positioned when the state is  `headroom--top`, but I'd like to add padding to the body to prevent the "jump" from happening when the element goes to fixed while `headroom--pinned`.

**Comment by WickyNilliams** [comment]
This should be possible as it stands. You have a few options:

---

Pass body to the Headroom constructor:

```js
var hr = new Headroom(document.body);
hr.init();
```

Then have your CSS hook into this:

```css
.headroom-pinned header {
  transform: translateY(0%);
}
.headroom--unpinned header {
  transform: translateY(-100%);
}
```

---

Alternatively, you could hook into the `onPin` and `onUnpin` callbacks, and pass your header to the Headroom as usual:

```js
var hr = new Headroom(myHeaderElement, {
  onPin : function() {
    document.body.classList.add("whatever");
  },
  onUnpin : function() {
    document.body.classList.remove("whatever");  
  },
});
hr.init();
```

Your CSS needn't change for this approach.

---

Take your pick :)
