### ISSUE TITLE
Using headroom for menu at bottom

### ISSUE THREAD

**Issue by nikreations** [WickyNilliams/headroom.js#304]
Is it possible to have the menu bar at the bottom and get the same functionality? i.e. scroll down to reveal the bottom menu, scroll up to hide the bottom menu.

**Comment by WickyNilliams** [comment]
Sure. This should work, assuming the element has a class `header`

```css
.header {
  position: fixed;
  bottom: 0;
} 

.headroom--pinned {
  transform: translateY(100%);
} 

.headroom--unpinned {
  transform: translateY(0);
}
```
