### ISSUE TITLE
Can’t have a smooth transition when going up (headroom--unpinned)?

### ISSUE THREAD

**Issue by Chacapamac** [WickyNilliams/headroom.js#322]
I made an example here —> http://www.graf-test.ca/pulvoy2/index.php/fr/evenements-kite-trips

Trying and trying to have a smooth transition when Headroom is going up, under the fold, no success?

**My CSS:**
`/*----------------------- HEADROOM --------*/
#sunfw_section_header.headroom {
    will-change: transform;
	transition: transform 300ms ease-in-out;
}
#sunfw_section_header.headroom--top {
	position:relative !important;
	top:inherit !important;
	background-color:transparent !important;
}
#sunfw_section_header.headroom--pinned {
	position: fixed;
	width: 100%;
	top: 0px;
    transform: translateY(0%);
	-webkit-transition: translateY(0%);
	-moz-transition: translateY(0%);
	-o-transition: translateY(0%);
	z-index:1000;
	background-color: rgba(0,0,0,0.7);
}
#sunfw_section_header.headroom--unpinned {
    transform: translateY(-100%);
	-webkit-transition: translateY(-100%);
	-moz-transition: translateY(-100%);
	-o-transition: translateY(-100%);	
}
/*------------------- END HEADROOM --------*/`

**Comment by hacknug** [comment]
Can't transition between `position` values. Header should always be fixed if that's whan you need, and then use `.headroom--STATE` to change its background-color.

Something like this _might_ work:
```css
#sunfw_section_header.headroom {
  z-index: 1000;
  position: fixed;
  top: 0px;
  right: 0;
  left: 0;
  will-change: transform;
  transition: transform 300ms ease-in-out;
}

#sunfw_section_header.headroom--top {
  background-color: transparent;
}

#sunfw_section_header.headroom--pinned {
  background-color: rgba(0, 0, 0, 0.7);
  transform: translateY(0%);
}

#sunfw_section_header.headroom--unpinned {
  transform: translateY(-100%);
}
```
