### ISSUE TITLE
Nothing happen on Chrome

### ISSUE THREAD

**Issue by kopax** [WickyNilliams/headroom.js#375]
Hello, I am trying to use headroom.js on this template:

https://open.cruip.com/

The classes are changing on my header while I scroll, but the css does not display anything and it stays up, this is my css:

```css
header.site-header {
  .headroom {
    will-change: transform;
    transition: transform 200ms linear;
  }
  .headroom--pinned {
    transform: translateY(0%);
  }
  .headroom--unpinned {
    transform: translateY(-100%);
  }
}
```

Is this still maintained?
